#pragma once

#define ARCHIVE_WIFI_ENABLED 0
#define ARCHIVE_BLE_ENABLED 0
#define ARCHIVE_MQTT_ENABLED 0
#define ARCHIVE_HTTP_SERVER_ENABLED 0
#define ARCHIVE_MODBUS_TCP_ENABLED 0
#define ARCHIVE_OTA_ENABLED 0

#define ARCHIVE_WIFI_MAX_RETRY 5
#define ARCHIVE_WIFI_COMMAND_TIMEOUT_MS 5000
#define ARCHIVE_BLE_COMMAND_TIMEOUT_MS 5000
#define ARCHIVE_MQTT_COMMAND_TIMEOUT_MS 5000

#define ARCHIVE_DEVICE_NAME "archive-plc"
#define ARCHIVE_MQTT_CLIENT_ID "archive-plc-001"
#define ARCHIVE_MQTT_TOPIC_STATUS "archive/plc/001/status"
#define ARCHIVE_MQTT_TOPIC_ALARM "archive/plc/001/alarm"
#define ARCHIVE_MQTT_TOPIC_COMMAND "archive/plc/001/command"
